services:
  pitch-elevator:
    build: .
    ports:
      - "8080:8080"
    environment:
      OPEN_API_KEY: ${OPEN_API_KEY}
      OPEN_AI_MODEL: ${OPEN_AI_MODEL}
      OPEN_AI_TEMPERATURE: ${OPEN_AI_TEMPERATURE}
